from functools import lru_cache

from azure.identity import DefaultAzureCredential, get_bearer_token_provider
from langchain_community.vectorstores.azuresearch import AzureSearch
from langchain_openai import AzureChatOpenAI, AzureOpenAIEmbeddings

from .config import get_settings


@lru_cache
def get_credential() -> DefaultAzureCredential:
    return DefaultAzureCredential()


@lru_cache
def get_llm() -> AzureChatOpenAI:
    s = get_settings()
    token_provider = get_bearer_token_provider(
        get_credential(), "https://cognitiveservices.azure.com/.default"
    )
    return AzureChatOpenAI(
        azure_endpoint=s.azure_openai_endpoint,
        api_version=s.azure_openai_api_version,
        azure_deployment=s.azure_openai_chat_deployment,
        azure_ad_token_provider=token_provider,
        temperature=0.2,
    )


@lru_cache
def get_embeddings() -> AzureOpenAIEmbeddings:
    s = get_settings()
    token_provider = get_bearer_token_provider(
        get_credential(), "https://cognitiveservices.azure.com/.default"
    )
    return AzureOpenAIEmbeddings(
        azure_endpoint=s.azure_openai_endpoint,
        api_version=s.azure_openai_api_version,
        azure_deployment=s.azure_openai_embedding_deployment,
        azure_ad_token_provider=token_provider,
    )


@lru_cache
def get_vector_store() -> AzureSearch:
    s = get_settings()
    cred = get_credential()

    # AzureSearch accepts a callable that returns a fresh AAD access token
    # for the Azure AI Search data plane.
    def token_supplier() -> str:
        return cred.get_token("https://search.azure.com/.default").token

    return AzureSearch(
        azure_search_endpoint=s.azure_search_endpoint,
        azure_search_key=None,  # use AAD via DefaultAzureCredential
        index_name=s.azure_search_index,
        embedding_function=get_embeddings().embed_query,
        # NOTE: these field names must match the schema of the index that
        # was generated by your Knowledge Base. Inspect the index in the
        # Azure portal (Search service -> Indexes -> Fields) and update
        # these values if they differ.
        content_key="chunk",
        vector_key="text_vector",
        azure_ad_access_token_provider=token_supplier,
    )
